# Generated by Django 5.0.6 on 2024-07-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('id_number', models.CharField(max_length=13)),
                ('direct_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('has_experience', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('previous_companies', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution_method', models.TextField()),
                ('distribution_area', models.CharField(max_length=255)),
                ('rica_access', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('required_networks', models.CharField(max_length=255)),
                ('best_networks', models.CharField(max_length=255)),
                ('vat_registered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('average_activations', models.CharField(max_length=45)),
                ('preferred_communication', models.CharField(max_length=45)),
                ('airtime_solution', models.TextField(blank=True, null=True)),
                ('hear_about_us', models.CharField(choices=[('Friend referred me', 'Friend referred me'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
