# Generated by Django 5.0.6 on 2024-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_application_other_method_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(auto_now=True),
        ),
    ]
