# Generated by Django 5.0.6 on 2024-07-09 05:07

from django.db import migrations

def add_commercials(apps, schema_editor):
    CommercialSchedule = apps.get_model('dealer', 'CommercialSchedule')
    CommercialSchedule.objects.create(name='Commercial Schedule A1')
    CommercialSchedule.objects.create(name='Commercial Schedule A2')
    CommercialSchedule.objects.create(name='Commercial Schedule B1')
    CommercialSchedule.objects.create(name='Commercial Schedule B2')


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_commercialschedule_dealercommercial'),
    ]

    operations = [
        migrations.RunPython(add_commercials),
    ]
