# Generated by Django 5.0.6 on 2024-07-23 07:24

from django.db import migrations

def add_doc_type(apps, schema_editor):
    # Get the DocumentType model from the student app
    DocumentType = apps.get_model('dealer', 'DocumentType')

    # Define the document type to be added
    doc_types = [
        'ID Number/Passport',
        'Proof of Bank Account',
        'Proof of Residence',
        'Live Photo',
    ]

    # Add document types to the database
    for doc_type in doc_types:
        if not DocumentType.objects.filter(doc_type=doc_type).exists():
            DocumentType.objects.create(doc_type=doc_type)


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_documenttype_document'),
    ]

    operations = [
        migrations.RunPython(add_doc_type)

    ]
