# Generated by Django 5.0.6 on 2024-09-17 11:53

from django.db import migrations

def update_commercials(apps, schema_editor):
    CommercialSchedule = apps.get_model('dealer', 'CommercialSchedule')

    # Update the names based on the current values
    CommercialSchedule.objects.filter(name='Commercial Schedule A1').update(name='Free Stock 1')
    CommercialSchedule.objects.filter(name='Commercial Schedule A2').update(name='Free Stock 2')
    CommercialSchedule.objects.filter(name='Commercial Schedule B1').update(name='Buying Stock 1')
    CommercialSchedule.objects.filter(name='Commercial Schedule B2').update(name='Buying Stock 2')



class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_application_vat_number'),
    ]

    operations = [
        migrations.RunPython(update_commercials),
    ]
